<!-- yml->xml -->
zkports: "2888,3888"
configFile: "/var/zoo.cfg"
binDir: "/opt/zookeeper"
zkconfig:
  tickTime: "1999"
  dataDir: "/var/lib/zookeeper/"
  clientPort: "2181"
  initLimit: "5"
  syncLimit: "2"
